name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 18 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update submodule
      uses: textbook/git-checkout-submodule-action@2.1.1
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          docs/_build
          sphinx
        key: v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install gettext
        python -m pip install --upgrade pip
        pip install Sphinx
        pip install -r docs/requirements.txt
    - name: Download PO from Weblate
      run: |
        mkdir -p weblate/docs
        mkdir -p weblate/classes
        curl https://hosted.weblate.org/download/godot-engine/godot-docs/zh_Hant/ -o ./weblate/docs/zh_TW.po
    - name: Update
      run: |
        ./update.sh -st
        ./update.sh -so
    - name: Build
      run: |
        cd docs
        READTHEDOCS_LANGUAGE=zh_TW make -e SPHINXOPTS="-D language='zh_TW'" html
        touch _build/html/.nojekyll
    - name: Publish
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/_build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

