name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@2.1.1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Sphinx
        pip install -r docs/requirements.txt
    - name: Download PO from Weblate
      run: |
        curl https://hosted.weblate.org/download/godot-engine/godot-docs/zh_Hant/ -o ./weblate/docs/zh_TW.po
    - name: Update
      run: |
        ./update.sh -st
        ./update.sh -so
    - name: Build
      run: |
        cd docs
        make -e "-D language='zh_TW'" html
    - name: Publish
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branche: gh-pages
        build_dir: docs/_build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

